### ISSUE TITLE
Generate Code from .json Doctype Definitions

### ISSUE THREAD

**Issue by keeduardo** [klahap/fraplin#3]
Currently, the plugin generates code by fetching the doctype definitions from a running site. It would be highly beneficial to have the ability to generate code directly from Frappe's doctype definition .json files. This enhancement would eliminate the necessity of having a running site, streamlining the code generation process.

Proposed Solution:

Add functionality to the plugin that allows it to read and generate code from the .json files of Frappe's doctype definitions.

Benefits:
- Removes the dependency on a running site for code generation.
- Simplifies the development workflow.
- Makes the plugin more versatile and easier to use in different environments.

Additional Information:

Please let me know if further details or clarifications are needed. Thank you!

**Comment by klahap** [comment]
Hi @keeduardo

Great news! We've added this feature in the brand new version 2.1.0. 🎉 You can now generate code directly from Frappe's doctype definition .json files without needing a running site. Check out the README for detailed instructions on how to use it.

If you have any questions or need further assistance, feel free to ask!
